name: Pre-commit checks
on: [push, pull_request]

jobs:
    run-pre-commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - name: Install uv
              uses: astral-sh/setup-uv@v7
              with:
                  version: latest
                  enable-cache: true
                  cache-dependency-glob: "uv.lock"
                  github-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Run pre-commit
              run: uv run prek run --all-files
